notices =[
    {
        '_id': '1',
        'title': 'Happy New Year',
        'image':'../images/holiday.png',
        'description':'this is description about new year holiday.',
        'date_published':'sunday 5th-Oct. 2024',
    },
    {
        '_id': '2',
        'title': 'local holiday',
        'image':'../images/holiday1.png',
        'description':'this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.',
        'date_published':'Thursday 7th-Dec. 2024',
    },
    {
        '_id': '3',
        'title': 'Dashain vactation',
        'image':'../images/holiday2.jpg',
        'description':'this is description about Dashain & Tihar vactation.',
        'date_published':'sunday 6th-Nov. 2024',
    },
    {
        '_id': '4',
        'title': 'chhath parva',
        'image':'../images/OIP.jpeg',
        'description':'this is description about chhath vactation.',
        'date_published':'Friday 6th-Sept. 2024',
    },
    {
        '_id': '5',
        'title': 'chhath parva',
        'image':'../images/OIP.jpeg',
        'description':'this is description about chhath vactation.',
        'date_published':'Friday 6th-Sept. 2024',
    },
    {
        '_id': '6',
        'title': 'Democracy Day',
        'image':'../images/holiday1.png',
        'description':'this is description about chhath vactation.',
        'date_published':'Friday 6th-Sept. 2024',
    },
    {
        '_id': '7',
        'title': 'local holiday',
        'image':'../images/holiday1.png',
        'description':'this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.',
        'date_published':'Thursday 7th-Dec. 2024',
    },
    {
        '_id': '8',
        'title': 'local holiday',
        'image':'../images/holiday1.png',
        'description':'this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.this is description about local holiday.',
        'date_published':'Thursday 7th-Dec. 2024',
    },
]
